<?php

return [
    'css' => [
        'assets/fontawesome512/all.css',
        'assets/css/animate.min.css',
        'assets/confirm/confirm.css',
        'assets/select2/select2.css',
        'assets/sumoselect/sumoselect.css',
        'assets/datetimepicker/jquery.datetimepicker.css',
        'assets/daterangepicker/daterangepicker.css',
        'assets/rangeSlider/ion.rangeSlider.css',
        'assets/filer/jquery.filer.css',
        'assets/filer/jquery.filer-dragdropbox-theme.css',
        'assets/holdon/HoldOn.css',
        'assets/holdon/HoldOn-style.css',
        'assets/simplenotify/simple-notify.css',
        'assets/comment/comment.css',
        'assets/css/adminlte.css',
        'assets/css/adminlte-style.css',
    ],
    'js' => [
        'assets/js/jquery.min.js',
        'assets/js/moment.min.js',
        'assets/confirm/confirm.js',
        'assets/select2/select2.full.js',
        'assets/sumoselect/jquery.sumoselect.js',
        'assets/datetimepicker/php-date-formatter.min.js',
        'assets/datetimepicker/jquery.mousewheel.js',
        'assets/datetimepicker/jquery.datetimepicker.js',
        'assets/daterangepicker/daterangepicker.js',
        'assets/rangeSlider/ion.rangeSlider.js',
        'assets/js/priceFormat.js',
        'assets/jscolor/jscolor.js',
        'assets/filer/jquery.filer.js',
        'assets/holdon/HoldOn.js',
        'assets/sortable/Sortable.js',
        'assets/js/bootstrap.js',
        'assets/js/adminlte.js',
        'ckeditor/ckeditor.js',
        'assets/apexcharts/apexcharts.min.js',
        'assets/simplenotify/simple-notify.js',
        'assets/comment/comment.js',
        'assets/js/apps.js',
    ],
];

